# Generated by Django 4.2.30 on 2026-09-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=50, unique=True)),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('location_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['location_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('record_id', models.CharField(db_index=True, max_length=100)),
                ('location_id_raw', models.CharField(blank=True, max_length=100)),
                ('event_date_raw', models.CharField(blank=True, max_length=100)),
                ('category_code', models.CharField(blank=True, max_length=100)),
                ('actor_id', models.CharField(blank=True, max_length=100)),
                ('base_value_raw', models.CharField(blank=True, max_length=100)),
                ('adjustment_raw', models.CharField(blank=True, max_length=100)),
                ('total_value_raw', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('import_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('entry_id', models.CharField(max_length=100)),
                ('record_ref_raw', models.CharField(blank=True, max_length=100)),
                ('normalized_ref', models.CharField(db_index=True, max_length=100)),
                ('location_id_raw', models.CharField(blank=True, max_length=100)),
                ('recorded_on_raw', models.CharField(blank=True, max_length=100)),
                ('value_raw', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('import_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
